:library: Asciidoctor
:toc:
:toc-placement!:

=  Notes: Chapter 1 - 12

The Benefits of Offline First +
To go back to the README where all the chapters are: click link:README.asciidoc[here].

toc::[]

== 01.01: first 

rable - Are identifiable as “applications” thanks to W3C
manifests[6] and service worker registration scope allowing search
engines to find them. +
Re-engageable - Make re-engagement easy through features like push
notifications. +
Installable - Allow users to “keep” apps they find most useful on their
home screen without the hassle of an app store. +
Linkable - Easily shared via a URL and do not require complex
installation. +
Progressive Web Apps described by Shoaib in a follow-up post:[7] are an
enhancement of existing web technology. As such, they do not require
separate bundling or distribution. Publication of a Progressive Web App
is as it would be for 

== 01.02: second

some text

----
cd pwd git init
----

== 01.03: third

this is a link: https://somewebsite.com[exampleLink]

== 2.1: Intro

We first meet our instructors: *Jake Archibald* from London who will do
most of the teaching. *Mike Wales* from USA who gives us the quizzes.
Jake goes on to show the importance of having offline first. He says
that what we will be working on will work great on whatever type of
connection. We will be working on the dev tools, IDB the in browser
database, use user interface strategy to deal varying network conditions
and updates.

== 2.2: The Problem

Jake talks about an app we will be working on. It's not quite a
progressive app yet, but what we will work on is to make it progressive.
So what does progressive app mean? +
 +

___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
*https://en.wikipedia.org/wiki/Progressive_web_app[Progressive app]*: +
In 2015, designer Frances Berriman and Google Chrome engineer Alex
Russell coined the term "Progressive Web Apps" [3] to describe apps
taking advantage of new features supported by modern browsers, including
service workers and web app manifests, that let users upgrade web apps
to progressive web applications in their native operating system (OS).
According to Google Developers,[3][4][5] these characteristics are: +
 +
Progressive - Work for every user, regardless of browser choice because
they’re built with progressive enhancement as a core tenet. +
Responsive - Fit any form factor: desktop, mobile, tablet, or forms yet
to emerge. +
Connectivity indepreplacementent - Service workers allow work offline,
or on low quality networks. +
App-like - Feel like an app to the user with app-style interactions and
navigation. +
Fresh - Always up-to-date thanks to the service worker update process. +
Safe - Served via HTTPS to prevent snooping and ensure content hasn’t
been tampered with. +
Discoverable - Are identifiable as “applications” thanks to W3C
manifests[6] and service worker registration scope allowing search
engines to find them. +
Re-engageable - Make re-engagement easy through features like push
notifications. +
Installable - Allow users to “keep” apps they find most useful on their
home screen without the hassle of an app store. +
Linkable - Easily shared via a URL and do not require complex
installation. +
Progressive Web Apps described by Shoaib in a follow-up post:[7] are an
enhancement of existing web technology. As such, they do not require
separate bundling or distribution. Publication of a Progressive Web App
is as it would be for any other web page. As of 2017, Progressive Web
Apps are supported by the Chrome browser, but more browsers may support
the features needed in the future. +
 +
The technical baseline criteria for a site to be considered a
Progressive Web App by browsers were described by Russell in a follow-up
post:[8] +
 +
Originate from a Secure Origin. Served over TLS and green padlock
displays (no active mixed content). +
Load while offline (even if only a custom offline page). By implication,
this means that Progressive Web Apps require Service Workers. +
Reference a Web App Manifest with at least the four key properties:
name, short_name, substr_url, and display (with a value of standalone or
fullscreen) +
An icon at least 144×144 large in png format. E.g.: "icons": [ \{ "src":
"/images/icon-144.png", "sizes": "144x144", "type": "image/png" } ] +
___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


== 2.3: The Benefits of Offline First

Offline first means getting as much content as possible from the cache
then the internet only _if_ we _can_ get content from the network. + 
If you do get content from the network, all new information will get stored into the
cache. If you just can't get content from the network, we just use what
is in the cache. It might be outdated, but at least it's better than
nothing.



== 2.5: Quiz: What Does Online First Look Like

The quiz website is online first, so if the network is offline, it will pull
something from the cache for fallback content or special page for
offline. +

In which of the following conditions will our app work well? +
*a*. Good connection. +
*b*. Bad connection. +
*c*. Offline +

*Summary:* Mike is mainly trying to tell you that offline first
is better since online first will struggle horribly on bad connection
type of networks. So the answers are A and C.

=


some code
A normal paragraph.

 A paragraph offset by at least one space becomes a literal paragraph.
 All lines in a literal paragraph must be adjacent.

 A literal paragraph is displayed as preformatted text.
 The text is shown in a fixed-width font.
 Spaces and newlines,
 like the ones in this sentence,
 are preserved.

Another normal paragrap‰.


NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.A normal paragraph.

 A paragraph offset by at least one space becomes a literal paragraph.
 All lines in a literal paragraph must be adjacent.

 A literal paragraph is displayed as preformatted text.
 The text is shown in a fixed-width font.
 Spaces and newlines,
 like the ones in this sentence,
 are preserved.

Another normal paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...